# Generated by Django 4.0.1 on 2022-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=50, null=True)),
                ('breed', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
